# TCL File Generated by Component Editor 22.1
# Mon May 22 20:03:09 MSK 2023
# DO NOT MODIFY


# 
# Timer "Timer" v1.0
# RB 2023.05.22.20:03:09
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module Timer
# 
set_module_property DESCRIPTION ""
set_module_property NAME Timer
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR RB
set_module_property DISPLAY_NAME Timer
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL timer
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file timer.sv SYSTEM_VERILOG PATH RTL/timer.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter FREQUENCY_VALUE INTEGER 50000000
set_parameter_property FREQUENCY_VALUE DEFAULT_VALUE 50000000
set_parameter_property FREQUENCY_VALUE DISPLAY_NAME "Frequency value"
set_parameter_property FREQUENCY_VALUE TYPE INTEGER
set_parameter_property FREQUENCY_VALUE ENABLED false
set_parameter_property FREQUENCY_VALUE UNITS None
set_parameter_property FREQUENCY_VALUE HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point avmms
# 
add_interface avmms avalon end
set_interface_property avmms addressUnits WORDS
set_interface_property avmms associatedClock clock
set_interface_property avmms associatedReset reset_n
set_interface_property avmms bitsPerSymbol 8
set_interface_property avmms burstOnBurstBoundariesOnly false
set_interface_property avmms burstcountUnits WORDS
set_interface_property avmms explicitAddressSpan 0
set_interface_property avmms holdTime 0
set_interface_property avmms linewrapBursts false
set_interface_property avmms maximumPendingReadTransactions 0
set_interface_property avmms maximumPendingWriteTransactions 0
set_interface_property avmms readLatency 0
set_interface_property avmms readWaitTime 1
set_interface_property avmms setupTime 0
set_interface_property avmms timingUnits Cycles
set_interface_property avmms writeWaitTime 0
set_interface_property avmms ENABLED true
set_interface_property avmms EXPORT_OF ""
set_interface_property avmms PORT_NAME_MAP ""
set_interface_property avmms CMSIS_SVD_VARIABLES ""
set_interface_property avmms SVD_ADDRESS_GROUP ""

add_interface_port avmms avmms_address address Input 2
add_interface_port avmms avmms_write write Input 1
add_interface_port avmms avmms_writedata writedata Input 32
add_interface_port avmms avmms_byteenable byteenable Input 4
add_interface_port avmms avmms_read read Input 1
add_interface_port avmms avmms_readdata readdata Output 32
set_interface_assignment avmms embeddedsw.configuration.isFlash 0
set_interface_assignment avmms embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avmms embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avmms embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset_n
# 
add_interface reset_n reset end
set_interface_property reset_n associatedClock clock
set_interface_property reset_n synchronousEdges DEASSERT
set_interface_property reset_n ENABLED true
set_interface_property reset_n EXPORT_OF ""
set_interface_property reset_n PORT_NAME_MAP ""
set_interface_property reset_n CMSIS_SVD_VARIABLES ""
set_interface_property reset_n SVD_ADDRESS_GROUP ""

add_interface_port reset_n reset_n reset_n Input 1


# 
# connection point coe_interrupt
# 
add_interface coe_interrupt conduit end
set_interface_property coe_interrupt associatedClock clock
set_interface_property coe_interrupt associatedReset ""
set_interface_property coe_interrupt ENABLED true
set_interface_property coe_interrupt EXPORT_OF ""
set_interface_property coe_interrupt PORT_NAME_MAP ""
set_interface_property coe_interrupt CMSIS_SVD_VARIABLES ""
set_interface_property coe_interrupt SVD_ADDRESS_GROUP ""

add_interface_port coe_interrupt coe_interrupt coe_interrupt Output 1

